services:
  app: 
    platform: linux/amd64
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
      - GO_VERSION=${APP_GO_VERSION}
      - GO_OS=${APP_GO_OS}
      - GO_ARCH=${APP_GO_ARCH}
      - GO_PROXY=${APP_GO_PROXY}
    container_name: app
    # restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT_INTERNAL:-5432}
      DB_USER: ${DB_USER:-developer}
      DB_PASSWORD: ${DB_PASSWORD:-qwerty123}
      DB_NAME: ${DB_NAME:-weather_station}
      APP_PORT: ${APP_PORT_INTERNAL:-8080}
    volumes:
      - ./src/templates:/app/templates
    ports:
      - "${APP_PORT_EXTERNAL:-8080}:${APP_PORT_INTERNAL:-8080}"
    networks:
      - weather-station
    depends_on:
      db:
        condition: service_healthy

  migration:
    build:
      context: .
      dockerfile: ./docker/migration/Dockerfile
    container_name: migration
    entrypoint: []
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT_INTERNAL:-5432}
      DB_USER: ${DB_USER:-developer}
      DB_PASSWORD: ${DB_PASSWORD:-qwerty123}
      DB_NAME: ${DB_NAME:-weather_station}
    networks:
      - weather-station
    depends_on:
      db:
        condition: service_healthy
  
  db: 
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-weather_station}
      POSTGRES_USER: ${DB_USER:-developer}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-qwerty123}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_EXTERNAL:-5432}:${DB_PORT_INTERNAL:-5432}"
    networks:
      - weather-station
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-developer} -d ${DB_NAME:-weather_station}"]
      interval: 10s  
      timeout: 5s
      retries: 5
  
  frontend-build:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend-build
    environment:
      APP_BASE_URL: ${APP_BASE_URL:-http://localhost:8080/api/v1}
      API_BASE_URL: ${API_BASE_URL:-http://localhost:8080}
      TIMEZONE_OFFSET: ${TIMEZONE_OFFSET:-4}
    working_dir: /frontend
    volumes:
      - ./frontend/src:/frontend/src
      - ./src/templates/static/dist:/frontend/dist
    command: ["npm", "run", "build"]
    profiles:
      - build

  frontend-watch:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend-watch
    environment:
      APP_BASE_URL: ${APP_BASE_URL:-http://localhost:8080/api/v1}
      API_BASE_URL: ${API_BASE_URL:-http://localhost:8080}
      TIMEZONE_OFFSET: ${TIMEZONE_OFFSET:-4}
    working_dir: /frontend
    volumes:
      - ./frontend/src/:/frontend/src/
      - ./src/templates/static/dist:/frontend/dist
    command: ["npm", "run", "watch"]
    profiles:
      - dev

volumes:
  db_data:
    driver: local

networks:
  weather-station:
    driver: bridge